image: docker.io/gitpod/workspace-full

tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

jetbrains:
  plugins:
    - org.intellij.scala